### ISSUE TITLE
Tns info is not work on downloaded projects

### ISSUE THREAD

**Issue by kumaran-dena** [NativeScript/nativescript-angular#1031]
I have downloaded the [lazyNinjas app](https://github.com/sis0k0/lazyNinjas) from github. I have build and tested in my local machine. From this app if tried to check components versions information using tns info means i have encountered with Invalid Version:next error.

FYI,
![tnsinfodown](https://user-images.githubusercontent.com/30895291/31337662-f9c94e70-ad19-11e7-8be3-0b9539d72ffc.PNG)

How can check all NativeScript components versions information belongs to an downloaded nativescript apps from github/any other source.

Regarding this i have raised the topic on NS forum [thread.](https://discourse.nativescript.org/t/tns-info-is-not-work-on-downloaded-projects/2787)

**Comment by NickIliev** [comment]
Hey @kumaran-dena 

The issue is because in [the lazyNinja project the runtimes](https://github.com/sis0k0/lazyNinjas/blob/aot/package.json#L8-L13) are references with `next`.
The thing is that these are not treated as npm packets by nativescript CLI and in the same time the command `tns info` is looking for packages in NPM published with the described version.

To overcome this issue just remove the `next` version for `tns-ios` and `tns-android` and prepare your project with published versions.

e.g.
```
    "tns-android": {
      "version": "3.2.0"
    }
```

**Comment by kumaran-dena** [comment]
@NickIliev  As you told, Its works fine once i added the actual version of runtimes instead of next.

My doubt is what Its showing tns-core-modules current version as 3.3.0-2017-9-28-2. But in package.json it was setted as  "tns-core-modules": "^3.2.0". 

FYI,
![tnsinfonext](https://user-images.githubusercontent.com/30895291/31374929-86e47548-adbd-11e7-9bdb-43ea07462678.PNG)
