### ISSUE TITLE
Issues in Groceries guide(Angular)

### ISSUE THREAD

**Issue by jvdonk** [NativeScript/nativescript-angular#1059]
In chapter 3.3, when moving the login.html template out to a separate file, the tutorial points to the app/pages/login/login.html file. But that's not where the AppComponent is looking for: ./login.html.

So, the to proceed with the tutorial, one must create a new app/login.html file and paste the contents of the template to proceed with the tutorial.

In chapter 3.4, the signUp functionality is changed in the AppComponent but there is no mentioning of updating the login.html template to point to the newly created signUp function.

So, the tap event of the second button should be changed to: (tap)="signUp()" instead of (tap)="toggleDisplay()" to be able to use the new signUp function and proceed with the tutorial

BTW, thank you for the excellent easy startup guides, appreciated!

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/sample-Groceries#276

**Comment by AkshayKannan-V** [comment]
Heyy there,
I am following the same guide for creating a Groceries App. 
The Compiler keeps tagging "this.toggleDisplay()" under 

`
signUp() {
    this.userService.register(this.user)
      .subscribe(
        () => {
          alert("Your account was successfully created.");
          this.toggleDisplay();
        },
        () => alert("Unfortunately we were unable to create your account.")
      );
  }
`
Due to this, there is a run time error in my application.
I tried creating a new login.html page like @jvdonk had suggested. It didnt work for me.
I also tried switching the second button 'tap' to SignUp.
Still shows the same error.
Any ideas on how to proceed??
