### ISSUE TITLE
Nested ListView does not work properly

### ISSUE THREAD

**Issue by blueberrynotblue** [NativeScript/nativescript-angular#1069]
tns --version=3.3.0. my modules are all updated.
### Listview got some problem when nested.
```
<ListView [items]="myItems">
    <ng-template let-item="item">
        <Label [text]="item.groupName"></Label>
                <ListView [items]="item.list"> ----- **will only get one label below(list.length large than 1)**
                          <ng-template let-groupItem="item">
                                  <Label [text]="groupItem.name"></Label>
                          </ng-template>
                </ListView>
    </ng-template>
</ListView>
```
### ngfor works fine. 
```
<ListView [items]="myItems">
    <ng-template let-item="item">
        <Label [text]="item.groupName"></Label>
                <Label *ngFor="let groupItem of item.list" [text]="groupItem.name"></Label>  **--ngfor works fine**
    </ng-template>
</ListView>
```
Is this a bug?

**Comment by NickIliev** [comment]
@blueberrynotblue nested ListViews are not supported scenario due to some native limitations of the controls that lie behind ListView. 

Technically you can workaround it by using `ListView` and `ngFor` structural directive for the inner list as shown in [this demo application](https://github.com/NickIliev/NS-Issues/tree/master/nativescript-angular/issue_1069_ng). However, we should use a similar approach **with caution** due to possible performance issues especially if you plan to load large data source for the nested `ngFor`.
The ListView[ is virtualized and using recycling](https://medium.com/@alexander.vakrilov/faster-nativescript-listview-with-multiple-item-templates-8f903a32e48f) to significantly improve performance, while `ngFor` is not using any of those so use it only in a scenario where you would want to iterate in a limited amount of items. Using `ngFor` with a large source of items will cause to run out of memory and eventually have `OutOfMemory` error related issues.
