### ISSUE TITLE
Angular bindings not fired from Application events and EventListener callbacks

### ISSUE THREAD

**Issue by bumbella** [NativeScript/nativescript-angular#1076]
Hi,
I want label show if device portrait and hide when device is landscape.
```
constructor(){
    App.on('orientationChanged', (args)=> {
        console.log(args.newValue)
        if( args.newValue === 'landscape' ) { this.isLandscape = true; } else { this.isLandscape = false; };
    });
}

```
html:
`<label *ngIf="!isLandscape" [text]="user.cardId"></label>`

The args console. log the portrait and landscape but the variable this.isLandscape not hide the label. Please help me what is the wrong in my code
Thanx
Miklos

**Comment by NickIliev** [comment]
@bumbella the issue is related to [this one](https://github.com/NativeScript/nativescript-angular/issues/651)

As a workaround wrap the binding code in an Angular zoned callback as follows
```
import { Component, NgZone } from "@angular/core";

...

constructor(private itemService: ItemService, private zone: NgZone) {
    app.on('orientationChanged', (args) => {
        console.log(args.newValue);

        this.zone.run(() => {
            if (args.newValue === 'landscape') { 
                this.isLandscape = true; 
            } else { 
                this.isLandscape = false; 
            };
        })
    });
}
```

Demo poroject demonstrating the above technique can be found [here](https://github.com/NickIliev/NS-Issues/tree/master/nativescript-angular/issue_1076)
