### ISSUE TITLE
css not working on dynamic form with webpack

### ISSUE THREAD

**Issue by Serge-SDL** [NativeScript/nativescript-angular#1125]
Hello,

I found somethink that looks like an issue: css is not applyed to form fields in dynamic form when using webpack:
- it works well using tns run android
- no css with npm run start-android-bundle

I have created a simple projet to reproduce the issue: https://github.com/Serge-SDL/nativescript-webpack-issue

result without webpack (tns run android):
![image](https://user-images.githubusercontent.com/1452002/34081901-4ab13246-e355-11e7-8ebe-f4ca01ba99a6.png)

result with webpack (npm run start-android-bundle):
![image](https://user-images.githubusercontent.com/1452002/34081942-09cc3482-e356-11e7-9436-cae13ada0adb.png)

Thansks!

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/nativescript-dev-webpack#359

**Comment by tsonevn** [comment]
Hi @Serge-SDL,
Thank you for reporting this issue, 
I reviewed it and confirm that this is a real problem, I also found that this problem is already reported [here](https://github.com/NativeScript/nativescript-dev-webpack/issues/257#issuecomment-333249539). As a workaround, you could use `ngClass` instead of `class`, which will also allow applying the styling dynamically. For example:
```
<StackLayout [formGroup]="form">
            <StackLayout *ngFor="let prop of objectProps">
                <label [text]="prop.label"></label>
                <TextField [formControlName]="prop.key" [id]="prop.key" [ngClass]="prop.cssClass"></TextField>
            </StackLayout>
            <Label [text]="form.value | json"></Label>
        </StackLayout>
```

**Comment by Serge-SDL** [comment]
Ok thanks for informations and workaround! works well 👍
