### ISSUE TITLE
navigate back multiple times with one step

### ISSUE THREAD

**Issue by cindy-m** [NativeScript/nativescript-angular#1167]
In the app where I am currently work on, we have a situation where the user can navigate 4 pages down, with everywhere the possibility to go back one step. At the end of page 4, the user needs to be navigated back to page 2, with the back button in page 2 still working. So, actually go back 2 steps with just one animation.
I could not find how to this with the routerExtension in any way. Use Frame.goBack(to:BackStackEntry) works to navigate back to the second page, but when the user than taps back to the first page, the navigation brakes and it is not possible to move to the second page anymore (all other navigations to other path that was not used before does work correctly). 

Is there a way to go back more than one page in just one step without clearing the whole history so that the back button still works on that page?

I found this issue already in stacklayout where they have the same problem: https://github.com/NativeScript/NativeScript/issues/3848

But I could not implement the suggested solution myself, (at least not without changing the code of NativeScript-angular itself and that is something we absolutely don't want)

**Comment by tsonevn** [comment]
Hi @cindy-m,
At this time similar functionality does not exist for NativeScript Angular. As you can see in issue #3848 this is a new feature, which is still under review. Regarding that, the discussed option for using `BackstackEntry` is not recommended because it will break the navigation.

Something that I would suggest is to make the [navigation with clear history](https://docs.nativescript.org/core-concepts/angular-navigation#clearing-page-navigation-history) option or to navigate back to the[ goBack() method ](https://docs.nativescript.org/core-concepts/angular-navigation#navigating-back) as time as it needed.

**Comment by cindy-m** [comment]
@tsonevn is it possible to see somewhere what the status is of this new feature? So that we can implement and use it as soon as it will be released

**Comment by tsonevn** [comment]
Hi @cindy-m,
You could keep track of issue [#3848](https://github.com/NativeScript/NativeScript/issues/3848).
We will update its status when we start working on it.

Hope this is applicable for you

**Comment by franculeto** [comment]
Any update for this issue?

**Comment by androidovshchik** [comment]
Another way is to use `clearHistory` property
```
    let frame = frameManager.topmost();
    const navigationEntry = {
        moduleName: '/views/main-page/main-page',
        clearHistory: true
    };
    frame.navigate(navigationEntry);
```
