### ISSUE TITLE
[Android] Suspend app issue

### ISSUE THREAD

**Issue by trunkovich** [NativeScript/nativescript-angular#1243]
Suspend/resume app doesn't work while you are working in dev mode(I mean you just start application using `tns run android`). If you close application(completely) and run it from phone, suspend/resume will start working as expected.

steps to reproduce:
```
tns create --ng test-suspend
cd test-suspend
tns run android

When app starts, go to items details
Press home button to suspend the app
Press app icon to resume the app
It will show items list component

Completely close the app,
Press app icon to start the app
When app starts, go to items details
Press home button to suspend the app
Press app icon to resume the app
It will show item details page as expected
```

**Comment by kamok** [comment]
I was running into something similar, I tested your steps and replicated perfectly on a real device.

However, in my issue, I'm unable to resume successfully at all even after disconnecting and running from phone. Everything inside my `page-router-outlet` is gone until my next navigation.

**Comment by NickIliev** [comment]
@trunkovich this is actually expected behavior due to the difference in the way Android opens a suspended app and when opening an inactive app through the app icon (see here for more information)

Setting `launchMode` in the AndroidManifest (to the desired value) can resolve your issue depending on what behavior you are after.
