### ISSUE TITLE
Feature req: Directly modify navigation stack

### ISSUE THREAD

**Issue by bhavincb** [NativeScript/nativescript-angular#1244]
How to remove a particular pages from navigation ??
Let say

I am navigating to page2 from page1, page 3 from page2 and so on like this page1 ->page2->page3->page4->page5.

now i want to remove page2 and page4 from stack so that when user clicks hardware back button i want navigation to behave like this page5->page3->page1->exit

There is currently no direct way to modify the navigation stack. so please mark it as feature request. because there are many use-cases available where we need to modify navigation stack. this feature should be implemented when using angular.

**Comment by tsonevn** [comment]
Hi, @bhavincb,
This issue seems to be related to [this feature request](https://github.com/NativeScript/NativeScript/issues/3848), where it is requested providing a simple way to control the back stack entry in NativeScript Angular.

**Comment by bhavincb** [comment]
hii @tsonevn ,
i think both cases is some what difference. issue you had mentioned is related to functionality using which we can go to some page in Navigation Stack and feature i had mentioned is about modifying Navigation stack like removing and adding pages.

**Comment by tsonevn** [comment]
HI @bhavincb,
Adding and removing a page, while changing the Navigation stack, might be risky and could lead to issues with the navigation. Regarding that, the use case should be appropriately clarified. Also, I have mentioned that both issues are related because while allowing the Navigation stack back navigation, we should think about adding the requested from you functionality.
Please leave your comment on the other issue by providing the use cases and if there is an interest from the other users, we will discuss if there is a simple way to provide similar functionality.

**Comment by hackerunet** [comment]
What about clearing full history AFTER navigating, I cannot use the clearHistory true because it breaks the application for the bug #5743 neither I can update the core to 4.2 because we are very close to the release, so how can I prevent android users use the nav back button of the os without using the guard?, I just need to clear the history after getting to the destination module so the user cannot navigate back.

**Comment by tsonevn** [comment]
Hi @hackerunet,
Using the [clearHistory](https://docs.nativescript.org/angular/core-concepts/angular-navigation#clearing-page-navigation-history) will clear the entire navigation history. This property will prevent the user from going back to all pages previously visited.

**Comment by hackerunet** [comment]
Yes but i cannot use it as a property with navigate because of another bug
in NS that it's been trigered.

**Comment by tsonevn** [comment]
Hi @hackerunet,
You can try to overwrite the Android back button functionality. Check the blog post [here](https://www.thepolyglotdeveloper.com/2018/05/override-android-back-button-nativescript-angular-application/).

**Comment by hackerunet** [comment]
Thats what i did, also had to set the pullBack gesture on ios to false and
it was good enough, thanks.

**Comment by prabudevarrajan1** [comment]
Any update on this feature for Nativescript angular to modify the navigation stack
