### ISSUE TITLE
ERROR Error: java.lang.IllegalStateException: Cannot call this method while RecyclerView is computing a layout or scrolling

### ISSUE THREAD

**Issue by bhavincb** [NativeScript/nativescript-angular#1297]
here is playground demo
[https://play.nativescript.org/?template=play-ng&id=Am3Ebf&v=2](https://play.nativescript.org/?template=play-ng&id=Am3Ebf&v=2)

if we use only `[items]="images"` with RadListView instead of `[items]="images.slice(0,10)` then error goes away and everything works as expected.
but we have a use case where we want only portion of array as RadListView items that is why i'm using `Array.slice()` method.

**Comment by NickIliev** [comment]
@bhavincb instead of slicing the array in the binding, you could do that operation with the source and then pass the resulted array as a binding source. The `RadListView` also comes with a number of functionalities that can handle different source handling. Data operations like filtering, ordering are covered [here](https://docs.telerik.com/devtools/nativescript-ui/Controls/Angular/ListView/data-operations)). There is also [load-on-demand](https://docs.telerik.com/devtools/nativescript-ui/Controls/Angular/ListView/load-on-demand) and [pull-to-refresh](https://docs.telerik.com/devtools/nativescript-ui/Controls/Angular/ListView/pull-to-refresh) if you want to add more items manually.

If you still need to slice the source you could do it in your component by reassigning the sliced array.

For example, something like this:
```
ngOnInit(): void {
    this.images = this.images.slice(0, 10);
    console.log(this.images.length); // 10
}
```

**Comment by bhavincb** [comment]
hii @NickIliev ,
thankx for quick response, but i'm using nested RadListView. parent and child RadListView both have very large dataset. and i'm need of displaying only half data of child RadListView. so if i go with your approach and initialize different variable for every parent RadListView which contains half of child RadListView then i will be run out of memory soon.
that is the reason why i had raised issue.
because *ngFor works completely fine with runtime slicing.

**Comment by NickIliev** [comment]
@bhavincb `*ngFor`  is a structural directive with no optimizations whatsoever while the `RadListView` is using techniques like virtualization and recycling of cells to provide better performance when working with large sets of data. I can't fully understand your structure - perhaps you could provide a sample project to demonstrate why you can't slice the source object before it is passed to the boun `items` property

**Comment by bhavincb** [comment]
hii @NickIliev ,
here is playground
[https://play.nativescript.org/?template=play-ng&id=8l3mBp&v=3](url)

in above playground i only want to show half of `group.images` not all. keep in mind that this just a demo dataset object. actual data i'm working with is more complex and has more properties.

**Comment by NickIliev** [comment]
@bhavincb the nested listview scenario is not supported (neitherListView nor RadListView). The reason is that as mentioned before both components are using recycling to reuse already used cells (while the user scroll up/down the hidden cells are used to  create the new ones and this way the performance is greatly 
 improved as we only have to create cells for the visible elements and not for all items in the list). This said when you have a nested listview it cannot be reused as the info inside the cell is ..another list of items with reused cells. 

Apart from that, I noticed that you are using structural directives (***ngIf**) inside the listview cell. This again will break the performance or even the whole listview as cells are now different in structure and cannot be reused. Instead of using Angular directives to change the visual tree, use item templates to create different cells depending on the item data and logic. This way you will not break the list nor you will lose the performance. More details about this can be found[ in this blog post](https://medium.com/@alexander.vakrilov/faster-nativescript-listview-with-multiple-item-templates-8f903a32e48f). More details about using item templates in RadListView (to use instead of *ngIf) can be found [here](https://docs.telerik.com/devtools/nativescript-ui/Controls/Angular/ListView/multiple-templates).

**Comment by bhavincb** [comment]
@NickIliev , i had already reviewed those posts. but i have use case where i have to show list inside the another list. and for that use case i din't find any post or related data.
if one have UI requirement of nesting dataset then what will be the best approach performance wise for implementing that View?

**Comment by bhavincb** [comment]
hii @NickIliev , any update on what to do if UI requirement is Nested data?

**Comment by NickIliev** [comment]
@bhavincb consider using several different list-view based on the fetched data (or use item template). Or flatten/normalize the data once it is fetched The limitation of using `ListView` and having a performance-optimized application is that you can not nest list views inside other list views.
