### ISSUE TITLE
ElementRef's nativeElement passed with @Input() is undefined

### ISSUE THREAD

**Issue by tsonevn** [NativeScript/nativescript-angular#1322]
_From @ninodinatale on May 13, 2018 21:41_

### Tell us about the problem
Please see the code in the playground:
https://play.nativescript.org/?template=play-ng&id=uXOtU4&v=5

The `nativeElement` in the `RegisterComponent` fetched with `@ViewChild()` is defined, where it isn't in the `FormInputComponent` passed with `@Input()`.

I wanted to add an event listener in the `FormInputComponent` to the element.

_Copied from original issue: NativeScript/NativeScript#5813_

**Comment by vakrilov** [comment]
Hey @NativeScript/administrators 
The reason the element is not available in the `FormInputComponent` is because its `ngAfterViewInit` is fired **before** the `ngAfterViewInit` hook of the `RegisterComponent`. The `ViewChild` is not initialized at that time.

In your case it makes more sense to use `@ContentChild` for selecting the element, because you are selection it form the content passed to the `FormInputComponent`. Here is a link to playground:
https://play.nativescript.org/?template=play-ng&id=uXOtU4&v=7

Hope that helps.

**Comment by ninodinatale** [comment]
Hey @vakrilov 
That makes sense, thanks for the clarification.

Another follow up question: Is it possible to fetch NativeScript's UI elements such as TextField in `@ContentChildren` like it is possible with components and directives?

Thank you!

**Comment by vakrilov** [comment]
You can check [this answer](https://github.com/dart-lang/angular/issues/587#issuecomment-324247357) from the angular repo - looks like you can mark multiple elements with same template variable name and use it as a query.
