### ISSUE TITLE
Can not listen page.on events in root AppComponent

### ISSUE THREAD

**Issue by liuwei108** [NativeScript/nativescript-angular#1442]
### If there is no issue for your problem, tell us about it
Getting error:

> JS: bootstrap: ERROR BOOTSTRAPPING ANGULAR
> JS: bootstrap: Cannot read property 'on' of null

If I put this.page.on(...) listener in root AppComponent constructor.
For example, adding:
```
this.page.on(Page.unloadedEvent, event => {
            console.log('unloadedEvent');
        })
```
in the constructor of  AppComponent, preview app and this error appear.
putting it in other components, no problem occur.

### Which platform(s) does your issue occur on?
- ALL devices

### Please, provide the following version numbers that your issue occurs with:

- CLI: latest 4.1.2

**Comment by NickIliev** [comment]
@liuwei108 in most cases (e.g. when using the default Angular template like `--ng`) you will have a `page-router-outlet` in the HTML template for AppComponent. For example"
app.component.html
```HTML
<page-router-outlet></page-router-outlet>
```

This would create a NativeScript's `Frame` and the Frame will create a `Page` instance for each of the components in the given page-router-outlet rooting table (on navigation). So it is expected that this instance can be accessed only in the related component file (e.g. ItemsComponent if you are creating the base Angular template with `--ng`)

If you need to add some code-behind logic in the root AppComponent, you could still do that but instead of `Page` instance use a toot layout.
For example:
```HTML
<GridLayout (loaded)="onGridLoaded($event)" unloaded="onGridUnloaded($event)">
    <page-router-outlet></page-router-outlet>
</GridLayout>

```

Another option is to use[ createFrameOnBootstrap](https://docs.nativescript.org/angular/core-concepts/angular-navigation#application-without-page-router-outlet) wihtout page-router-outlet. This would create the frame during the applicaiton bootstrap and then you will have a Page instance even in the `AppComponent`

**Comment by liuwei108** [comment]
Hi Nick,
My purpose is to get a event when I click android back button to quit app.
even I wrapped GridLayout with page-router-outlet, the GridLayout's unloaded event still not being invoked while I click android back button to quit the APP.

**Comment by NickIliev** [comment]
@liuwei108 perhaps you could directly access and overwrite the native application event.

For example (Android)
```TS
application.android.on(application.AndroidApplication.activityBackPressedEvent, function (args) {
    console.log("Event: " + args.eventName + ", Activity: " + args.activity);
    // Set args.cancel = true to cancel back navigation and do something custom.
});
```
