### ISSUE TITLE
How to programmatically select a tab?

### ISSUE THREAD

**Issue by igorls** [NativeScript/nativescript-angular#149]
The method described [here](https://docs.nativescript.org/ApiReference/ui/tab-view/HOW-TO.html) is not working with angular, maybe I need a way to reference the TabView component, any idea? I just need to change to a specific tab on a function call, but maybe this is a bigger issue.

**Comment by hdeshev** [comment]
You should be able to name your TabView as in `<TabView #myTab>`, and then use a `@ViewChild` field decorator to obtain an Angular `ElementRef` which in turn will contain a reference to the native TabView element.

Related to #141

**Comment by igorls** [comment]
Thanks Hristo, that helped a lot. I wasn't thinking that would work because there is no DOM, but it does.

**Comment by daniel-rfe** [comment]
Since I also stucked on this, I would like to share the way I handled this:
I could get the tabview reference through frameModule. Using frameModule.topmost() you will get the reference to the current frame that is inside a <TabViewItem>, and then by using "parent.parent" you will achieve the <TabView> element.

`<TabView>
  <TabViewItem>
    <Frame defaultPage="your page route"></Frame>
  </TabViewItem>
</TabView>`
`
  const frameModule = require('tns-core-modules/ui/frame');
  const tabView = frameModule.topmost().parent.parent;
  tabView.selectedIndex = n; //change actual active tab
`
