### ISSUE TITLE
Can't refresh RadListView items on Android 

### ISSUE THREAD

**Issue by ChristofferSkog21st** [NativeScript/nativescript-angular#1714]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):

⚠ Update available for component nativescript. Your current version is 5.1.0 and the latest available version is 5.1.1.
⚠ Update available for component tns-core-modules. Your current version is 5.1.1 and the latest available version is 5.1.2.
✔ Component tns-android has 5.1.0 version and is up to date.
✔ Component tns-ios has 5.1.1 version and is up to date.
Angular - 7.1.4
 
**Describe the bug**
When trying to refresh the list using 2 different methods, one causes the app to crash and the other one doesn't do anything.

```
<RadListView #listview [items]="items"></RadListView>

...
@ViewChild('listview') radListView: RadListViewComponent;

...
updateItems() {

  this.http.get(...).subscribe((res) => {
      // Doing only this does nothing at all on both IOS and Android, calling refresh is needed
      this.items = [...this.items, res];

     // Throws error on Android, works in IOS
     // ERROR Error: java.lang.IllegalStateException: Cannot call this method while RecyclerView is computing a layout or scrolling
     this.radListView.listView.refresh();
  });
}
```

**To Reproduce**
See above code.

**Expected behavior**
I expect the list to update the items it's showing.

We cannot deliver the app because of this bug and I can't seem to find any workarounds. Please help.

**Comment by ChristofferSkog21st** [comment]
After doing some testing it appears as if it's the async http call that causes this issue. If I do it synchronous with test data it works as expected, but doing it synchronous isn't possible with http anymore so I don't know how to work around this.

**Comment by ChristofferSkog21st** [comment]
@NickIliev Any response?

**Comment by csi-stasik** [comment]
Did you use the ObservableArray?

```
<RadListView  [items]="items">
    <ng-template tkListItemTemplate let-item="item">
        <StackLayout>
            <Label [text]="item?.myprop"></Label>
         </StackLayout>
    </ng-template>
</RadListView>

...


updateItems() {
  this.http.get(...).subscribe((res) => {
      this.items = new ObservableArray<any>(res);
// or merging the existing items;
      this.items .concat(...res)
  });
}
```

**Comment by ChristofferSkog21st** [comment]
@csi-stasik No. Is that the only solution for Android?

**Comment by csi-stasik** [comment]
@ChristofferSkog21st, This is a generic solution. Also it is documented https://docs.nativescript.org/angular/ui/professional-ui-components/ng-ListView/getting-started

**Comment by NickIliev** [comment]
@ChristofferSkog21st the issue seems unrelated to nativescript-angular and related to RadListView. If you are still experiencing troubles finding the right approach then please post  your question [here](https://github.com/telerik/nativescript-ui-feedback)


Apart from that, you are not obligated to use `ObservableArray` and in the ideal case, you should not have to manually call `refresh`. I am suspecting that the listview is refreshing (thus the UI is updated/scrolling) and then you are calling the second refresh which is causing the error `Cannot call this method while RecyclerView is computing a layout or scrolling`. Either remove the refresh or call the method after the UI is updated from the original refresh

Trey with ssetTImeout
```TS
setTImeout(() => {
   this.radListView.listView.refresh();
}, 100)
```
