### ISSUE TITLE
iOS put content behind safe area

### ISSUE THREAD

**Issue by DanielRitvas** [NativeScript/nativescript-angular#1746]
Using nativescript + angular I have layout like this:

```
    <StackLayout backgroundColor="green">
        <StackLayout backgroundColor="red" height="300">
            <Image [src]="someUrl"></Image>
        </StackLayout>
    </StackLayout>
```
On android it allows me to achieve the desired result:
![image](https://user-images.githubusercontent.com/13576478/53093983-96b2bd80-3521-11e9-8a3f-0d0f2d2bab68.png)

As you may see, image falls behind the status bar and it's good in my case.
Meanwhile on iOS the same layout is rendered differently:

![image](https://user-images.githubusercontent.com/13576478/53093826-2b68eb80-3521-11e9-82a7-30a63a70ecd6.png)

My question is how can I achieve same look on iOS, as it's on android? So that image falls behind status bar.

**Comment by NickIliev** [comment]
@DanielRitvas the idea of the safe area is to prevent any app context (content) to be shown in this areas  - this way the content wont be hidded and unaccessible behind the notch.

Quote from  the official Apple documentation [here](https://developer.apple.com/design/human-interface-guidelines/ios/visual-design/adaptivity-and-layout/):

```
Adhere to the safe area and layout margins defined by UIKit. These layout guides ensure appropriate insetting based on the device and context. The safe area also prevents content from underlapping the status bar, navigation bar, toolbar, and tab bar. Standard system-provided views automatically adopt a safe area layout guide.
```

So that said you can't use the safe area to shown your **content** - think of the area os a must margin - you can apply background but the content will be spanned there.

See more about the safe are in NativeScript [here](https://docs.nativescript.org/ui/layouts/layouts#ios-safe-area-support)
