### ISSUE TITLE
Can not use @ViewChild with ActionBar

### ISSUE THREAD

**Issue by vahidvdn** [NativeScript/nativescript-angular#1764]
I want to access to ActionBar element to animate it. So I'm doing the following:

```HTML
<ActionBar #myActionBar class="action-bar">
    <Label class="action-bar-title" text="Home"></Label>
</ActionBar>
```

And in my ts file:
```TS
@ViewChild("myActionBar") myActionBar: ElementRef;
// ...
this.actionBar = this.myActionBar.nativeElement;
// ...
this.actionBar.animate({ ... })
```

I get the following error:
```
ERROR TypeError: Cannot read property 'animate' of undefined
```

**Note:** This works fine with any other element.

**Comment by NickIliev** [comment]
@vahidvdn indeed this is a limitation caused because we have on one side the Angular abstraction which loads the visual tree and on the other hand we have the mobile elements underneath.  SO in the case of ActionBar, we have an element which is dependent on a specific mobile architecture (e.g., the navigation bar on iOS), and these elements are not fully loaded or accessible when the ANgular component is loaded.
However, you could access the native element with the NativeScript `loaded` event.
For example:
```HTML
<ActionBar (loaded)="onActionBarLoaded($event)" ></ActionBar>
```

```TS
onActionBarLoaded(args: EventData) {
    const actionBar = args.object as ActionBar;
}
```

Note an event with the proper reference, you still will have limited possibilities to animate the ActionBar (again due to the same architecture specifics. Perhaps use page transition to apply animation)

**Comment by vahidvdn** [comment]
@NickIliev Thanks for the reply.

> in the case of ActionBar, we have an element which is dependent on a specific mobile architecture (e.g., the navigation bar on iOS), and these elements are not fully loaded or accessible when the Angular component is loaded.

So what is the different between ActionBar and a Label? Is your definition same for both?

> Perhaps use page transition to apply animation

I don't want to do anything during navigation, so nothing to do with the page transition. I want to collapse the ActionBar while scrolling. (Of course, I made it work with the custom layout, just wanted to know why this doesn't work)

**Comment by NickIliev** [comment]
@vahidvdn regarding `I want to collapse the ActionBar` you can use as a reference [this blog post](https://www.nativescript.org/blog/how-to-make-a-collapsible-custom-actionbar-in-nativescript) on how to achieve that while using custom action bar (layout implementation that mocks the real action bar).


Regarding your quesiton `So what is different between ActionBar and a Label? `

The ActionBar is actually special for iOS where behind the scenes the native control is [UINavigaitonBar](https://developer.apple.com/documentation/uikit/uinavigationbar?language=objc). This is not the typical UI element and it is closely related to the navigation controller. This said you can think of the ActionBar as a view that is supposed to be used as a navigation tool rather than as a classic UI element.

**Comment by vahidvdn** [comment]
@NickIliev I have already implemented the custom Actionbar. Just wanted to know about built-in ActionBar. Btw, thanks.
