### ISSUE TITLE
Bound rows and columns fields are not updated in GridLayout

### ISSUE THREAD

**Issue by lonerzzz** [NativeScript/nativescript-angular#1824]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
Playground version 1.7.0 running on android with the playground code mentioned below.
 
**Describe the bug**
When using the GridLayout, the bound rows and columns tags are not updated with changes made to the bound variables. So if the rows or columns information changes, this is not reflected in the layout of the grid. 

**To Reproduce**
See the Playground program seen below.

**Expected behavior**
If the rows and columns of the GridLayout can be bound, they should respond to changes in the underlying model values

**Sample project**
https://play.nativescript.org/?template=play-ng&id=dLJ5qR&v=2

**Additional context**

**Comment by lonerzzz** [comment]
@tsonevn I tested on android as mentioned in the Environment section so this is a bug in os:android and maybe os:ios if you tested it there.

**Comment by m-abs** [comment]
I don't think this is a bug in `nativescript-angular` but a common mistake when working with `angular`.

I see a few problems with your example:

1. The `orientationChanged`-event is triggered outside of Zone, so angular doesn't know the values have changed.
2. You're using functions to get the property values, this can be a performance killer since they have to execute everytime angular checks for update. Better to use values and update them once when needed.
3. Each `orientationChanged`-event triggers a new `setTimeout`-loop inside `updateButtonList`. If you need this loop, I'd add a `clearTimeout`.

A quick solution would be to use a `NgZone` and wrap `updateButtonList` with in a `zone.run(...)` like this.

```typescript
    constructor(private zone: NgZone) {
        this.buttonList = new Array<{ text: string }>();
        this.orientation = 'portrait';
        app.on('orientationChanged', (event: any) => {
            this.zone.run(() => this.updateButtonList(event.newValue));
        });
    }
```

**Comment by lonerzzz** [comment]
I tried your suggestion and it works. Thanks for broadening my understanding. I hadn't seen this response until now.
