### ISSUE TITLE
Dev Dependencies (like Gulp, etc) getting built and build is failing because of which Gulp integration is not working currently.

### ISSUE THREAD

**Issue by Headcult** [NativeScript/nativescript-angular#195]
Thanks for the amazing work on integrating Angular 2 with NativeScript at such a good pace. Looking forward for future releases.

The main issue that I'm facing now is:
Dev Dependencies (like Gulp, etc) getting built and build is failing because of which Gulp integration is not working currently.

Can this be fixed at the earliest as we are unable to use Gulp within our project when using Angular 2 and NativeScript?

**My Dev Dependencies:**

`"devDependencies": {
        "nativescript-dev-typescript": "^0.3.1",
        "shelljs": "^0.5.3",
        "typescript": "^1.8.9",
        "gulp": "^3.9.1",
        "gulp-debug": "^2.1.2",
        "gulp-typescript": "^2.12.1",
        "del": "^2.2.0",
        "run-sequence": "^1.1.4"
    }`

**Build Failure:**

`:processDebugResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processDebugResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.E
xecException: Process 'command 'C:\Android\android-sdk\build-tools\23.0.3\aapt.e
xe'' finished with non-zero exit value 1`

**Comment by hdeshev** [comment]
I finally reproduced the problem, and I believe this to be a problem with how nativescript-cli handles npm dependencies. Steps to reproduce:

1. Start an empty project.
2. Run it using `$ tns run android`
3. Install gulp: ` $ npm install gulp --save-dev`
4. `$ tns run android`

Working around the problem is easy, but not obvious -- don't call `npm`, but let the tns tool do that for you by adding gulp to your `package.json` and running `tns install` or just `tns run android`

**Comment by hdeshev** [comment]
This issue was moved to NativeScript/nativescript-cli#1740

**Comment by Headcult** [comment]
Thanks @hdeshev, will try with tns install and let you know. Thanks a ton for the quick response!
