### ISSUE TITLE
View is updated with delay in case of using back button and shared data service 

### ISSUE THREAD

**Issue by Nevaan** [NativeScript/nativescript-angular#2051]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.1.2
 - Cross-platform modules: - 
 - Android Runtime: 6.0.2
 - iOS Runtime: 6.0.2
 - Plugin(s): - 
 - NativeScript-Angular: 8.0.2
 - Angular: 8.1.2
 
**Describe the bug**
I have an application with two components: one is a list of elements, and the other is elements details. Both are sharing a service, which is a kind of store of displayed elements (details components modifies given element on the list too). When I go back with navigation button on top of the screen, in action bar, from details component to the list component (after modifying shared data), I can see a little delay with displaying new, changed data on list view.  I don't want to fetch all the data again on going back, and also I want to preserve the view at the same place when it navigated to the details. I am not sure if this approach is proper in this scenario (or even possible), so in case it is not, I would like to ask for advice how this can be achevied with nativescript.

**To Reproduce**
Here is playground reproducing the issue: https://play.nativescript.org/?template=play-ng&id=foWkYF

**Expected behavior**
ListView contains refreshed data instantly after showing it, when using 'back' button

**Comment by NickIliev** [comment]
I think the delay is caused due to the async pipe you are using. You could use plain JS array or an observable instead of async pipe with other functionality like LoadOnDemand or PullToRefresh (RadListView required for both). Still, I am not exactly sure what the issue is and what you are trying to archive - everything in your sample is working as expected.

Can you elaborate more on:
```
I don't want to fetch all the data again on going back, 
and also I want to preserve the view at the same place when it navigated to the details.
```

[Modified Playground](https://play.nativescript.org/?template=play-ng&id=foWkYF&v=3) (for test purposes)
