### ISSUE TITLE
NavigationButton Icon not loading initially in IOS

### ISSUE THREAD

**Issue by atchaiecommerce** [NativeScript/nativescript-angular#2090]
**Environment**
 - CLI:  6.2.0
 - Cross-platform modules: 6.2.0
 - iOS Runtime: 6.2.0
 - NativeScript-Angular: 8.2
 
**Describe the bug**
I'm trying to set an image back button in ios. Initial routing to the page does not load the image, however proceeding to the next page loads the back button image correctly and going back to the previous page also loads the correct image. I'm using a layout component that uses content projection. This layout component contains the shared code for the actionbar.
````
<ActionBar flat="true" backgroundColor="white">
    <NavigationButton icon="~/images/arrow_back_black.png" text="">
    </NavigationButton>

    <Label text="Demo Apps" color="black"></Label>
</ActionBar>

<StackLayout backgroundColor="lightgray">
    <Label text="Im a layout"></Label>

    <ng-content></ng-content>
</StackLayout>
````

**To Reproduce**
1. Home Page.
2. Go to Test 1 Component (Back button Image not loaded).
3. Go to Test 2 Component (black button image loaded). correct.
4. Go back to Test 1 Component (image shows). correct.

**Sample project**
https://play.nativescript.org/?template=play-ng&id=VTN9rv&v=19

**Comment by NickIliev** [comment]
@atchaiecommerce on my side with step 2 I am already seeing the back button. Are you testing on a specific device/iOS version?

**Comment by atchaiecommerce** [comment]
@NickIliev I'm using Iphone XR version 13.2.2. Step 2 really doesn't show the back button image on first load.

**Comment by atchaiecommerce** [comment]
I think it's only reproducible when using content projection. since setting up the action bar per page renders the back button correctly.

**Comment by NickIliev** [comment]
@atchaiecommerce well I would advise against using an angular custom component to re-create an ActionBar. The thing is that ANgular is the abstraction that lies over NativeScript, which is an abstraction that lies over the native platform (iOS or Android). So when you are creating an ActionBar in NativeScript, you are actually creating a [UINavigationController](https://developer.apple.com/documentation/uikit/uinavigationcontroller?language=objc) in iOS. This controller is responsible not only for the visual presentation of the "action bar" bit also for the whole navigation logic in iOS. So that said, you are using the Angular abstraction to reuse the UINavigationController visual representation which leads to the side effect you are experiencing. Code reusability is a good pattern but still, in this case, I would say to simply create your ActionBar for each component.

**Comment by atchaiecommerce** [comment]
@NickIliev thanks for your comment. I understand that some web concepts does not fully apply to mobile but in this case, it's a pain whenever you need to change the actionbar for all the pages.

I'm able to find a workaround which is to use the same actionbar on the homepage even tho it is hidden. this way the image will load on the next page.
