### ISSUE TITLE
NativeScriptModule 8.20.3 reported as not an Angular module by IntelliJ

### ISSUE THREAD

**Issue by jalberto-ghub** [NativeScript/nativescript-angular#2091]
Upgraded from nativescript-angular@8.2.1 to 8.20.3 and now IntelliJ complains the NativeScriptModule is not an Angular module.

Is there a problem with the meta-data on version 8.20.3? The module works fine but it is very annoying that it is not recognised properly.

**Comment by lini** [comment]
Perhaps the issue is that the `nativescript-angular` plugin moved to a scoped package name [@nativescript/angular](https://www.npmjs.com/package/@nativescript/angular) and the old plugin package is only kept for compatibility reasons (it just reexports everything from the scoped package). 

You can try migrating your app to the scoped package (`@nativescript/angular`) or simply ignore the errors since everything will compile and work the same with the old `nativescript-angular` package as well.
