### ISSUE TITLE
Apps close by backpress in not "home" page

### ISSUE THREAD

**Issue by juniorschen** [NativeScript/nativescript-angular#2293]
![image](https://user-images.githubusercontent.com/46031261/98609987-5c78e900-22cd-11eb-90ad-a73d6454f36f.png)

So I have a structure with just a lazy module that contains several children, one of these childrens is my "home" page, but no matter what child I am in, the app always closes ...

https://github.com/juniorschen/IGivenUp

what i hope:
![image](https://user-images.githubusercontent.com/46031261/98611040-d7430380-22cf-11eb-9081-6b2ab632b2b8.png)

Let the apps only close when I am on the "/ test" route, if it is in "/ test2" it should not close, I would not like to hear suggestions for signing up for backpress events :D

**Comment by nikoTM** [comment]
The framework has no way of knowing what you consider "home" screen, the back button will put the app in the background if navigation stack is empty (you are on the first Frame). In your case the only Frame that's created is FeatureComponent, since the other components are used in a `router-outlet`, if you want them to be part of native mobile navigation use `page-router-outlet`.

https://docs.nativescript.org/angular/core-concepts/angular-navigation#page-router-outlet 

https://github.com/NativeScript/nativescript-angular/issues/477

**Comment by juniorschen** [comment]
@nikoTM It is horrible to have to handle backpressed events, as this causes a headache with the modals, so I have a large volume of code that I would not need to have inside the app, but if this is really the only solution thank you
