### ISSUE TITLE
Profile and optimize tree insertion

### ISSUE THREAD

**Issue by hdeshev** [NativeScript/nativescript-angular#23]
We can probably do [better](https://github.com/NativeScript/nativescript-angular/wiki/Benchmarks) at inserting visual elements. The goal is to see if we can get somewhat closer to the browser performance.

**Comment by Krisa** [comment]
It may be related with the issue you reported - but I indeed noticed "relatively" slow performance by doing something relatively simple. I just took the todo sample application (https://github.com/NativeScript/sample-ng-todomvc) and displayed through a for loop 100 items (instead of 2). Then, once the application is loaded, I tried to delete one of the first item, and somehow, when looking at the logs, it redraws entirely the whole list and it blocks the UI for 3 to 5 seconds (not on an emulator but on my galaxy s4). On the opposite, deleting one of the last items (bottom) of the list, it redraws almost instantly.
