### ISSUE TITLE
View loaded event being called too soon?

### ISSUE THREAD

**Issue by vjoao** [NativeScript/nativescript-angular#250]
There is a plugin with this structure:

`class Plugin extends AbsoluteLayout { }`

and the `constructView` method does:

```
this.on(AbsoluteLayout.loadedEvent, (data: any) => {
    this.eachLayoutChild((view: View) => {

    .... some code with the children views   
 
    });
```

Because it's meant to be instantiated like that:
```
<PluginContainer>
    <SubView>
...
    </SubView>

    <SubView>
...
    </SubView>

    <SubView>
...
    </SubView>
</PluginContainer>
```

The problem is the `eachLayoutChild` is being called with no children whatsoever (looks like the `onLoad` event is being called before any child is constructed.

Is this the expected behavior? How to get the children list in this case?

**Comment by hdeshev** [comment]
Yes, at this moment the renderer creates parent views, attaches them to the visual tree (which fires their loaded events), and then proceeds with child views.

Since you are inheriting from a layout, perhaps it would be easiest if you override `_registerLayoutChild` and set up your children there:

https://github.com/NativeScript/NativeScript/blob/57d5bd143a0a60bc5867470966e66290bf7bb021/ui/layouts/layout-base.ts#L45-L51
