### ISSUE TITLE
How can i use proxy on http request?

### ISSUE THREAD

**Issue by nativescriptxamarin** [NativeScript/nativescript-angular#261]
read [angular 2 docs](https://angular.io/docs/ts/latest/api/http/Http-class.html) but seems like even proxy option does not exist.
I need to maintain proxy connection on entire application in every http reqeusts, so need this feature so much.
(because our country's censorship)

Is there any ways to figure out this problem? thanks.

**Comment by hdeshev** [comment]
Angular 2 is mostly a web framework and I doubt it will ever deal with proxy settings -- that's usually handled by the browser. NativeScript provides a HTTP implementation that wraps the system libraries. That's why [configuring](http://stackoverflow.com/a/21069032) a proxy there should take effect and all XMLHttpRequest connections should just use that proxy.

I just tested this with a local proxy and Android, and it seems to work just fine.
