### ISSUE TITLE
Support 2-way data binding (aka ng-model)

### ISSUE THREAD

**Issue by tjvantoll** [NativeScript/nativescript-angular#27]
One of the first things I wanted to do in my {N} + Angular 2 app was add a simple form, but I found it difficult since `<TextField [text]="foo">` only uses one-way data binding, and `<TextField [(ngModel)]="foo">` doesn’t work.

Can we some up with some way to incorporate Angular 2’s two-way data binding, ideally with the same `[(ngModel)]` syntax?

Thanks.

**Comment by hdeshev** [comment]
`[(ngModel)]="foo"` desugars to `[ngModel]="foo" (ngModelChange)="foo = $event"`, and we don't provide *Change events for most properties.

We could make this work for NativeScript dependency properties by attaching property change events automatically in the renderer whenever we get a `fooChange` event attach request.

This one needs more research, as I'm afraid we could easily end up with circular change events or zone exceptions (aka "causing a change during change detection").

**Comment by nsndeck** [comment]
@tjvantoll

After a #36 it is now possible to do two-way binding via '[ngModel]`. A sample usage should look similar to the following:

```XML
<Label [text]='model.test'></Label>
<TextField #name [ngModel]='model.test'></TextField>
```

Where model is {N} Observable.

**Comment by hackerunet** [comment]
How is this possible? I'm trying to build a simple login form and now after days learning and testing I found that 2 way DB is impossible with native script, so if this is not possible why TH NS released an angular version and it's promoting it as stable? Can you please provide an example? this is not working, if I place [ngModel] or [(ngModel)] or whatever I placed between brackets calling a model makes the application immediately crash, so, if this is not possible I wil have to alert the complete devs community to stay away from NS because honnestly it kind of feel like a scam. very disappointed.!!
