### ISSUE TITLE
SegmentationBar change updating model but not updating the UI

### ISSUE THREAD

**Issue by dotdreaming** [NativeScript/nativescript-angular#356]
I am having an issue with updating the UI when changing the index of a SegmentedBar component and I don't know if it is a bug or me not doing something right... sorry if this is the incorrect place for this. I have been trying to figure this out for ages with no succuss.

I started with trying to use the Segmented bar with angular/nativescript Router navigation. I could get the SegmentedBar to update the index of the bar and then fire a navigation change but the view didn't update any of the UI with dynamic data from the component.

So I simplified it a bit to have all of the UI rendered in the app.component, including the SegmentedBar. But again the same issue, I am checking for a change on the SegmentedBar and then updating the variable but its doesn't reflect the changes in the UI.

Is this a bug with the component or am I doing something wrong?

Please see the Gist for the code example:
[https://gist.github.com/dotdreaming/bf0502c31c3b6c7d8282737541bd5018](https://gist.github.com/dotdreaming/bf0502c31c3b6c7d8282737541bd5018)

**Comment by nsndeck** [comment]
Hi @dotdreaming,

The problem comes from the fact that you are changing values of the SegmentedBar.selectedIndex outside the angular2 zone and therefore change detection is not triggered and UI is not updated.
Change your code a little bit using a two-way binding:

```XML
<StackLayout class="ui-nav">
      <SegmentedBar #tabs [items]="items" [(ngModel)]="selectedIndex"></SegmentedBar>
</StackLayout>
```

Two way binding in angular2 works with a special directive `ngModel` which works with just one property in case of SegmentedBar it is `selectedIndex`.

This will do the job. You will not need the code inside `ngAfterViewInit` to attach a handler (which is outside the ZONE) to update `selectedIndex` property.

**Comment by dotdreaming** [comment]
Brilliant. I will give this a go. Thanks
