### ISSUE TITLE
Cannot specify platform visibility on ActionBar items

### ISSUE THREAD

**Issue by arnaudvalle** [NativeScript/nativescript-angular#361]
As per the documentation (http://docs.nativescript.org/angular/ui/action-bar.html#creating-slidedrawer-button), I use a NavigationButton and ActionItem to handle a sidedrawer menu button in both iOs and Android.

```
<ActionBar title="Hello">
    <NavigationButton icon="res://ic_menu" ios:visibility="collapse"></NavigationButton>
    <ActionItem icon="res://ic_menu" ios.position="left" android:visibility="collapse">
</ActionItem>
```

This used to work with nativescript-angular 0.1.6 and tns 2.0.0 but now breaks with my recent upgrade to tns 2.1.1 and nativescript-angular 0.2.0.

Now, both button just show up on Android.

Any idea if this is a bug or if there's a different / better way to do this now?

Thanks,

**Comment by NickIliev** [comment]
Hello @arnaudvalle 

Indeed platform-specific tags and attributes do not produce the expected behaviour within Actionbar.
I am closing this issues as duplicate to [https://github.com/NativeScript/nativescript-angular/issues/350](https://github.com/NativeScript/nativescript-angular/issues/350) - please track it's development and suggested solutions at the logged issue.

Closing as dulpicate to [https://github.com/NativeScript/nativescript-angular/issues/350](https://github.com/NativeScript/nativescript-angular/issues/350)

**Comment by arnaudvalle** [comment]
Ok, will do. Thanks @NickIliev
