### ISSUE TITLE
RouterExtensions class containing package

### ISSUE THREAD

**Issue by Dreamerpro** [NativeScript/nativescript-angular#380]
Not an issue but i couldn't find in anywhere. I am following [this](https://docs.nativescript.org/angular/core-concepts/navigation-angular.html#navigation-options) tutorial and stuck there. I couldn't find the package name containing `RouterExtensions `class from which i should import. Thanks.

**Comment by vakrilov** [comment]
Hi @Dreamerpro.
It is still not in the official release - but you can use it now if you switch to `@next` builds (#363 explains how to do that). Due to the high interest in the feature we updated the article a bit too early - the official release of the `nativescript-angular` package is coming soon too.

Sorry for the confusion.

**Comment by Dreamerpro** [comment]
Hi @vakrilov thanks for the info. Waiting eagerly the official release.
