### ISSUE TITLE
Offline template compilation

### ISSUE THREAD

**Issue by hdeshev** [NativeScript/nativescript-angular#386]
Things we need to figure out while providing offline compilation support:
- [x] ng modules and bootstrap-related changes.
- [x] Add a "static" platform similar to `platformNativeScriptDynamic`
- [x] integrating precompilation: invoking angular-cli vs. our own tools vs. webpack loader/plugin

Related to #385 (webpack dev workflow)

**Comment by Charlkie14** [comment]
Have you guys decided which one you will be taking? 
"angular-cli vs. our own tools vs. webpack loader/plugin"
Forgive me if I understand this wrongly but could you then potentially call the angular-cli with AOT (Ahead-of-time) to increase the startup time and lower the bundle size because the compiler doesn't have to ship?

**Comment by dxshindeo** [comment]
So what is the status on this? I see that NS 2.5 is available, but does that mean AoT compilation is also available?

**Comment by robertohuertasm** [comment]
From [here](https://www.nativescript.org/blog/nativescript-25-is-now-available):
> Ahead of Time (AoT) Compilation: When you install the nativescript-dev-webpack plugin, it comes with the AoT compiler enabled for Angular 2 applications.

**Comment by dxshindeo** [comment]
Thank you
