### ISSUE TITLE
An official web + mobile demo

### ISSUE THREAD

**Issue by hdeshev** [NativeScript/nativescript-angular#387]
Ship a demo project with web and mobile code using Angular 2.

- Share services code.
- Use a common UI theme.
- Bind to Firebase data using AngularFire2
- Use webpack for both platforms (#385)
- LiveSync/HMR friendly. (#268)

**Comment by lukabers** [comment]
+1

**Comment by sipacate** [comment]
In order to show this off at Angular Connect conference, we want to run this as a video, looping at the booth and as a post-release (NativeScript 2.3) webinar.
Main highlights:

Show Multi-browser, multi-mobile platforms and form factors with the same application. This video needs to be looped and of a reasonable length (5 min? 2 min?)

As such we'll need confirmation this asset will be in place, with enough time to engage the video services team.

**Comment by robbatt** [comment]
Would love to see this demo, can I find it on github?

**Comment by valentinstoychev** [comment]
Here it is:
https://www.nativescript.org/blog/angular-2-web-and-mobile-demo-app-using-kendo-ui-and-nativescript
