### ISSUE TITLE
angular2 rc6 app

### ISSUE THREAD

**Issue by denkomanceski** [NativeScript/nativescript-angular#445]
How to create an rc6 app with the CLI? it creates the old version that is using ```nativeScriptBootstrap(AppComponent);``` instead of NgModule? I updated to nativescript@latest and created a project with --ng

Any help?

**Comment by lachama** [comment]
Hello,

I'm facing the same problem, I would like to create an Angular app but the CLI is doing it with the rc4 and I would like to creat it with the rc6 so I can follow the current Router docs: http://docs.nativescript.org/angular/core-concepts/angular-navigation

**Comment by NickIliev** [comment]
Hey @denkomanceski , @lachama 

The base command with --ng will create an app with template published in **npm**

If you want to create an application using the latest/different template you can provide it as a param to the --template command.
e.g. (this will use the template from the link and from the release branch)
`tns create my-ng-app --template https://github.com/NativeScript/template-hello-world-ng`

if you want to specify a branch (e.g. master) you can do it like this
`tns create my-ng-app --template https://github.com/NativeScript/template-hello-world-ng#master`

You can also create your own temlpate and pass it with the 
tns create my-app --template [path-to-template]

The same applies not only to Angular but for TS templates and all others.

**Comment by lachama** [comment]
Hi @NickIliev, thanks a lot for the explanation, I guess I'm confused because the official docs for the Navigation are not based on the rc4 and even though the official documentation recommends this:

<img width="870" alt="screen shot 2016-09-13 at 10 50 44" src="https://cloud.githubusercontent.com/assets/9157362/18480939/15951fde-79a0-11e6-9621-60a2fff16cca.png">

there are some docs on the Nativescript official site that are based on the rc6 and that's a little bit confusing.

**Comment by NickIliev** [comment]
@lachama 

Indeed, at this very moment, the documentation is not fully updated for the usage of RC6 - we are working on the updates but also working on integration with RC7 so the article fix might be delayed.

**Comment by dtopuzov** [comment]
Obsolete, now we create apps with official release.
