### ISSUE TITLE
Using Item Template won't visualise the binded data

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/nativescript-angular#461]
_How to reproduce;_ 
Follow [**this article** ](https://docs.nativescript.org/ui/list-view#using-an-item-template) example or [this sdk example.](https://github.com/NativeScript/nativescript-sdk-examples-ng/tree/master/app/listview/using-item-template)

_Result:_ 
List-view won't visualize any data coming through **Input()** , nor the template <item-component> will load if the parent component has the following binding declaration
```
            <ListView [items]="myItems">
                <template let-item="item">
                    <item-component [data]="item"></item-component>
                </template>
            </ListView>
```

**Comment by chimon2000** [comment]
@NickIliev I had a similar issue. It ended up being because I wasn't registering `NativeScriptModule` inside of my feature module where I was using the ListView.

What's weird is that the other UI elements were working fine and I had `NativeScriptModule` declared on the app module, which I'd think should inject it everywhere.

**Comment by NickIliev** [comment]
From angular-rc6, we have to explicitly declare the components we are going to use in our application in our **@NgModule** (in this case in our **main.ts**)

fixed with [https://github.com/NativeScript/nativescript-sdk-examples-ng/pull/59](https://github.com/NativeScript/nativescript-sdk-examples-ng/pull/59)
