### ISSUE TITLE
SearchBar is invisible on iOS

### ISSUE THREAD

**Issue by tsonevn** [NativeScript/nativescript-angular#487]
_From @tjvantoll on October 3, 2016 16:51_
### Did you verify this is a real problem by searching [Stack Overflow]

Yes, I’m actually really surprised this has yet to be reported.
### Tell us about the problem

Start a new project with `tns create foo --ng`.

Change your `app.component.ts` to use the following code:

``` JavaScript
import { Component } from "@angular/core";

@Component({
    selector: "my-app",
    template: `
<StackLayout>
    <SearchBar hint="Search"></SearchBar>
</StackLayout>
`
})
export class AppComponent {}
```

If you run this app on Android you see a SearchBar as expected; if you run this app on iOS you see nothing.
### Which platform(s) does your issue occur on?

iOS
### Please provide the following version numbers that your issue occurs with:
- CLI: 2.3.0
- Cross-platform modules: 2.3.0 (also tried with `next` and had the same problem)
- Runtime(s): 2.3.0
- Plugin(s): None

Note: I’m running Xcode 8, which I have a feeling might have something to do with the problem.

Ping @nraboy, as he hit this issue as well.

_Copied from original issue: NativeScript/NativeScript#2833_

**Comment by tsonevn** [comment]
_From @nraboy on October 3, 2016 17:2_

+1

**Comment by tsonevn** [comment]
Hi @tjvantoll,
We will research what is causing this problem, however as a workaround you could  set in `app.css` the `StackLayout`to be with 100% width;
```
SearchBar{
    width: 100%;
}
```

**Comment by nraboy** [comment]
The work-around seems to work.  Definitely want a less hacky solution though :-)

**Comment by vakrilov** [comment]
Here is more detailed explanations what happens. In the default project template there is this selector in the `app.css`:
``` 
stack-layout {
    horizontal-align: center;    
}
```
Which tells the all `StackLayouts` to take only the space their content wants and then center themselves. In this case the empty `SearchBar` does not require any width and because there are no other elements to "stretch" the StackLayout - its width remains zero. It would be pretty much the same if you had a `TextBox` instead of the `SearchBar`.

If you clear the `app.css` completely you will get the desired result. StackLayout will stretch on the entire page width (the default behavior) and the `SearchBox` will also be stretched to take the full width of the `StackLayout`.

I hope this clarifies things

**Comment by nraboy** [comment]
It does, but I think you're going to have a ton of confused people when they run into the issue.  Are there any better solutions?

**Comment by vakrilov** [comment]
I don't think there is a better solution at this moment. 
In the next version [default project template](https://github.com/NativeScript/template-hello-world) - the `horizontal-align: center;` style is removed, so this setup is less likely to happen. 

Again, this problem will be visible only if the `search-bar` is the only view (or all the other views have 0 width) inside a container that is not stretched. Setting `width/minWidth` of the SearchBar will also make it visible.
