### ISSUE TITLE
Data bind on navigation

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/nativescript-angular#566]
_From @snekbaev on November 27, 2016 22:44_

Android, Nexus 5 with Marshmallow, NS 2.4.0. TS + NG. Plugins:
```
"nativescript-angular": "1.1.3",
"nativescript-direct-sms-send": "file:..\\nativescript_modules\\direct-sms-send",
"nativescript-messenger": "^1.2.0",
"nativescript-permissions": "^1.2.1",
"nativescript-ripple": "^1.0.1", 
```

While continuing my journey with NS and I'm working on my first app. App is very simple and meant for personal use, it is my playground and I'm trying to get as best performance as possible. Current question is related to loading the data on navigation. I have "home" and "history" views. "Home" view has a link that takes user to the "history" view, which lists user smses: small image (set of 2) and the formatted date. Initially I used the ListView and NG's DatePipe and formatted the value in the markup. Tested the transition and noticed a bit of a delay before "history" view pops up, also ListView scrolling wasn't smooth enough. Then I decided to remove the DatePipe from the markup and rather apply it in the component directly to the data before assigning to the items property, so that ListView will render only simple text output, that made the scrolling super smooth. However, navigation lag was still there: a noticeable delay when I tap the "go to history" button. I traced it to the DatePipe's transform function.

Eventually what I wanted is to preprocess the data as much as possible beforehand and not do that on the main thread. So my next solution was to use a worker which does the heavy lifting now (via momentjs). Now navigation is instantaneous```*``` and "history" view immediately loads with a activity indicator and then data comes. This way app feels way more responsive.

Thus, the question: is my understanding correct that when any data preprocessing is needed, even for simple cases like formatting the date basically I have to do that via workers to get the best UX, what eventually means that I probably should start doing nearly all my data binding via workers.

```*```when app is newly started and first ever navigation is done - there is a small initial delay, **usually** doesn't happen when doing back-forward after that.

Thank you!

_Copied from original issue: NativeScript/NativeScript#3182_

**Comment by snekbaev** [comment]
@nsndeck please download it from https://github.com/NativeScript/NativeScript/issues/3180#issuecomment-263279171 and use the following ListView:

```
<ListView [items]="listItems" rowHeight="60">
        <template let-item="item">
                <StackLayout>
                    <Image [src]="item.image"></Image>
                    <Label [text]='item.date | date : "H:m:ss EEEE, d MMMM y"' textWrap="false" style="padding-left:10;"></Label>
                </StackLayout>
        </template>
</ListView>
```

meanwhile I will try to implement a version that uses date pipe with templates for ListView

**Comment by snekbaev** [comment]
Tested with templates:

```
 <ListView [items]="listItems" rowHeight="60" [itemTemplateSelector]="templateSelector">
         <template nsTemplateKey="odd" let-item="item">
            <StackLayout class="odd">
                <Image [src]="item.image"></Image>
                <Label [text]='item.date | date : "H:m:ss EEEE, d MMMM y"' textWrap="false" style="padding-left:10;"></Label>
            </StackLayout>
        </template>

        <template nsTemplateKey="even" let-item="item">
            <StackLayout class="even">
                <Image [src]="item.image"></Image>
                <Label [text]='item.date | date : "H:m:ss EEEE, d MMMM y"' textWrap="false" style="padding-left:10;"></Label>
            </StackLayout>
        </template>
    </ListView>
```

```
 public templateSelector = (item: any, index: number, items: any) => {
        return (index % 2) ? "odd" : "even";
    }
```

fast scrolling is not smooth either.

**Comment by snekbaev** [comment]
@nsndeck my initial question wasn't mainly about date pipe per se, but data preprocessing in general because I was getting a noticeable delay when navigating to the "history" view. Of course for some waiting around a second vs several hundreds of milliseconds might not be a big deal, but it just doesn't feel responsive enough to me. Moreover, it might take longer depending on the preprocessing. Refactoring to use worker very nicely improved the navigation UX: now it is reasonably fast, I can see the activity indicator and then the data shows up. However, worker based approach introduced own complexity and scattered the logic, nevertheless, it pays off by making things more responsive. Hopefully JS async/await will address this matter better, just like it is possible in Xamarin now.

**Comment by nsndeck** [comment]
@snekbaev Indeed using workers is a great option for improve UX look and feel. I asked for example since there are maybe something else which causes the delay. At the first place I saw a custom pattern for date pipe which is not the perfect case, since there are more native calls compared to a named pipe like `fullDate`. The funny thing is that we support such pattern, but when it is passed via `angular2` there is an issue. I'll investigate and will share what I found here.

**Comment by snekbaev** [comment]
@nsndeck 

a) I believe the delay is caused by the first/initial time that logic executes, that is whatever NS does there **and** by the fact that I did data preprocessing on the main thread: I fetched smses and each sms was piped through date pipe or momentjs (not via markup), that was done on UI thread which added up to the delay. Now I still have the initial navigation + firing up the worker extra delay. Yet this approach takes less time to converge.

b) I don't have NS experience without AngularJS, but while I was working on this test app I couldn't stop thinking that AngularJS overhead wasn't justified in my case: app startup time + size. Even if I skip these two I'm left with a bigger one: just because I have the power of NG it doesn't mean I can fully leverage from it, because doing certain things for "developer" convenience will ruin the UX for the end user. I'll try to come up with a more sophisticated test app next year and then try to get it done via pure NS and via NS + NG to validate or disprove my assumptions :)

**Comment by nsndeck** [comment]
@snekbaev I've just checked in a small optimization (some caching) for `nativescript-intl` plugin (which handles date pipe on nativescript side). Could you please try it with nativescript-intl - 0.0.8 and let me know about the result?
You may install it directly in app folder to override its dependency from nativescript-angular.
By the way you can place ListView inside GridLayout instead of StackLayout (this also will improve scrolling and UX experience)

**Comment by snekbaev** [comment]
@nsndeck could you please provide more detailed instructions on how to try it out. I'm new to npm and a naive attempt of ```tns plugin add nativescript-intl``` doesn't seem to work. My current packages:

```
{
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "org.nativescript.ListViewIssue",
    "tns-android": {
      "version": "2.4.1"
    }
  },
  "dependencies": {
    "@angular/common": "2.2.1",
    "@angular/compiler": "2.2.1",
    "@angular/core": "2.2.1",
    "@angular/forms": "2.2.1",
    "@angular/http": "2.2.1",
    "@angular/platform-browser": "2.2.1",
    "@angular/platform-browser-dynamic": "2.2.1",
    "@angular/router": "3.2.1",
    "nativescript-angular": "1.2.0",
    "nativescript-theme-core": "^0.2.1",
    "reflect-metadata": "~0.1.8",
    "rxjs": "5.0.0-beta.12",
    "tns-core-modules": "2.4.0"
  },
  "devDependencies": {
    "babel-traverse": "6.19.0",
    "babel-types": "6.19.0",
    "babylon": "6.14.1",
    "lazy": "1.0.11",
    "nativescript-dev-android-snapshot": "^0.*.*",
    "nativescript-dev-typescript": "^0.3.2",
    "typescript": "^2.0.10",
    "zone.js": "~0.6.21"
  }
}
```

**Comment by nsndeck** [comment]
Sorry for the delay.
Simple `npm install --save nativescript-intl` inside application root folder should be enough.

**Comment by snekbaev** [comment]
Hi,

did that, got ```"nativescript-intl": "0.0.8"``` in package.json:
```
{
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "org.nativescript.ListViewIssue",
    "tns-android": {
      "version": "2.4.1"
    }
  },
  "dependencies": {
    "@angular/common": "2.2.1",
    "@angular/compiler": "2.2.1",
    "@angular/core": "2.2.1",
    "@angular/forms": "2.2.1",
    "@angular/http": "2.2.1",
    "@angular/platform-browser": "2.2.1",
    "@angular/platform-browser-dynamic": "2.2.1",
    "@angular/router": "3.2.1",
    "nativescript-angular": "1.2.0",
    "nativescript-intl": "0.0.8",
    "nativescript-theme-core": "^0.2.1",
    "reflect-metadata": "~0.1.8",
    "rxjs": "5.0.0-beta.12",
    "tns-core-modules": "2.4.0"
  },
  "devDependencies": {
    "babel-traverse": "6.19.0",
    "babel-types": "6.19.0",
    "babylon": "6.14.1",
    "lazy": "1.0.11",
    "nativescript-dev-android-snapshot": "^0.*.*",
    "nativescript-dev-typescript": "^0.3.2",
    "typescript": "^2.0.10",
    "zone.js": "~0.6.21"
  }
} 
```

On fast scrolling issue remains.

**Comment by NickIliev** [comment]
@snekbaev is this issue still reproducible with the latest nativescript-angular and the latest Angular related versions? Both NativeScript and Angular have introduced a lot of performance improvements so please do let me know if you are still experiencing this case.

CLosing this one due to inactivity.

**Comment by snekbaev** [comment]
@NickIliev haven't used NS since, feel free to close for now. Thank you!
