### ISSUE TITLE
Improve Docs on DetachedContainer

### ISSUE THREAD

**Issue by ford04** [NativeScript/nativescript-angular#568]
Hi, 

recently i read some code snippets about `DetachedContainer` and `PlaceHolder` for Nativescript Angular, and thought that it could match my requirement:

Basically i want to create an Angular View from a template
```
let viewRef: EmbeddedViewRef<any> = this.viewContainer.createEmbeddedView(this.myTemplateRef);
viewRef.context.$implicit = myContext
```

But i want to add the created view with the native android `addView` method in an android `Viewgroup` directly - it is a kind of `ViewPager` implementation. So it should not be added to the visual tree by Angular. However, as i understand the method `createEmbeddedView` from `ViewContainerRef`, the ng views are placed in the visual tree.
I found the basics how to convert a NG view to a NS Core View in the [NS docs](https://docs.nativescript.org/angular/plugins/angular-third-party.html).

So my question would be:
1. Is  a DetachedContainer/ PlaceHolder suitable for this case ? (and what is their difference)
2. It would be great if you could improve the docs and provide a sample

Thanks in advance

**Comment by NickIliev** [comment]
Placeholder is only NativeSscript Core concept (not to be used in Angular!).

For Angular based app the ANgular approaches are the recommended and supported one so the best place for information related to DetachedContainer would be the Angular documentation.

**Comment by edusperoni** [comment]
@NickIliev I'm trying to do the same thing: instantiate an angular template (`createEmbeddedView`) into native views (or set them up for loading) so I can inject them into `nativescript-popup` and another plugin I'm developing.

`DetachedContainer` is a nativescript exclusive implementation with placeholder, so maybe it should be documented?

It would be really helpful for plugin developers if this was documented somewhere. Currently, an implementation similar to `ListView` is almost impossible without a direct copy of the code.

@triniwiz implemented `nativescript-accordion` with an almost complete copy of the current `ListView` implementation, and often that is not possible due to different native elements being used (`nativescript-accordion` uses `ExpandableListView`) or it's just a complete overkill.


I already tried to copy part of the `LIstView` code, but the `_addView` magic always results in `The specified child already has a parent`, and doing some hacks by manipulating the `nativeView` results in crashes when cleaning up the views.
