### ISSUE TITLE
Change the default template to include router

### ISSUE THREAD

**Issue by valentinstoychev** [NativeScript/nativescript-angular#581]
Based on the user testing we identified that it is hard for the newcomers to start using the NativeScript router. It will be good if we have a recommended implementation as part of the default hello world template when creating Angular apps.

This also needs to use lazy loading by default.

**Comment by lukashlobil** [comment]
Hi,
I wanted to help out, since I had pretty much the same setup. I [forked](https://github.com/lukashlobil/template-hello-world-ng) and implemented the desired changes, but failed to get the project running (tns-core-modules missing, on Android it complains about @drawables/icon and on iOS it complains about version of undefined). 
I couldn't test my code as I failed to run the project. How can I run the template-hello-world-ng project on my machine?

**Comment by matt4446** [comment]
and a flag for the current one ?
