### ISSUE TITLE
next tag: when using platformNativeScriptDynamic AppOptions custom css, 'application.setCssFileName' is undefined

### ISSUE THREAD

**Issue by NathanWalker** [NativeScript/nativescript-angular#586]
> file:///app/tns_modules/nativescript-angular/bundle.all.js:1022:39: JS ERROR TypeError: application.setCssFileName is not a function. (In 'application.setCssFileName(this.appOptions.cssFile)', 'application.setCssFileName' is undefined)

When doing the following:

```
import { platformNativeScriptDynamic } from 'nativescript-angular';

import { AppModule } from './app.module';

const platform = platformNativeScriptDynamic({cssFile: 'custom-named.css'});
platform.bootstrapModule(AppModule);
```

tns: `2.4.1`
nativescript-angular: `next`

**Comment by nsndeck** [comment]
Hi @NathanWalker,
Generally `nativescript-angular@next` depends on `tns-core-modules@next`. Unfortunately applications uses `tns-core-modules` from its dependency and problem arises, However since the change of `tns-core-modules` is very small we will release new version by the end of the week. Meanwhile update app's package.json with next as version to tns-core-modules.

**Comment by RoyiNamir** [comment]
@NathanWalker Hi. Does it work for you with `--bundle` ? 
I've reported it here : 
https://github.com/NativeScript/nativescript-dev-webpack/issues/587
