### ISSUE TITLE
getting crashed when parsing reponse using JSON

### ISSUE THREAD

**Issue by mohitgorakhiya** [NativeScript/nativescript-angular#599]
I am calling 1 API and getting response from API and when trying to parse into JSON then it gives error.
Here is my code,

**return this.http.post(Config.apiUrl, options) 
map((res:Response) => res.json()) 
catch((error:any) => Observable.throw(error.json().error || 'Server error'));** 

when res.json() will execute it will throw exception and gives below error:

**TypeError: error.json is not a function. (In 'error.json()', 'error.json' is undefined)**
I have import all possible module for this, still getting same error.
Can you please help me out to solve this?

**Comment by eleddie** [comment]
What I would normally do is:

`return this.http.post(url, body, options).map(res => res.json())`
`     .subscribe(`
`     successData=> {`
`     //success code`
`     }, err => {`
`     //error code`
     `});`

Note that the post method receives 3 parameters, so if you are not passing it a body variable but you are passing options then you should do something like:

`this.http.post(url, null, options).map(res => res.json())`

Because if you do it like this:

`this.http.post(url, options).map(res => res.json())`
the method is going to think that the options variable is the body.
You can try it.

**Comment by mohitgorakhiya** [comment]
Yes  I have also tried same but getting error.
I am getting error while executing res.json() function.
Solution provided by you will work?

**Comment by eleddie** [comment]
That's what I always do to make a request and it works.

Maybe you can post more of your code to see if there's something else that is causing the error

**Comment by NickIliev** [comment]
@mohitgorakhiya the crash appears when you are trying to parse your **error**.
Try to log the error before it is parsed to see what you're receving or try something like this:
```
this.myService.getData()
    .subscribe(
    (result) => this.onGetDataSuccess(result),
    (error) => this.onGetDataError(error)
);

// the callbacks for success and failure
private onGetDataSuccess(res) {
    // parse the successfully retrieved data
}

private onGetDataError(error: Response | any) {
    const body = error.json() || "";
    const err = body.error || JSON.stringify(body);
    console.log("onGetDataError: " + err);
}
```

Extended examples on how to work with HTTP in nativeScript+Angular-2 you can find [here](https://github.com/NativeScript/nativescript-sdk-examples-ng/tree/master/app/http)
