### ISSUE TITLE
Unanswered SO question - How to use angular navigation in modals

### ISSUE THREAD

**Issue by jamieathans** [NativeScript/nativescript-angular#603]
The following question has been posted on stack overflow but is currently unanswered so I am reposting it here as I would like to know the answer as well.

[How to use navigation in modals](http://stackoverflow.com/questions/39771855/nativescript-how-to-use-navigation-in-modals).

Is this use case supported with NativeScript angular 2?

**Comment by matt4446** [comment]
Would putting a child router in the modal template work for you?

**Comment by jamieathans** [comment]
@matt4446 By "child router" I assume you mean putting `<router-outlet>` in the modal page. Can the same page transition animation be achieved as when using the `<page-router-outlet>`?

**Comment by matt4446** [comment]
@jamieathans 
That's the one. Its been a few months (1/2 a year) since I've had any spare time with NativeScript. I'm not sure to be honest. Transitions in general were just coming in last time I was playing about with it. 

I would copy this sample into a project and give it a try (adding in transitions):
https://github.com/NativeScript/nativescript-angular/blob/master/ng-sample/app/examples/router/page-router-outlet-nested-test.ts

[Docs. Page transitions](https://docs.nativescript.org/core-concepts/angular-navigation#specifying-page-transitions)

One could animate the content to simulate a transition fairly easily if its not available.

**Comment by NickIliev** [comment]
@matt4446, @jamieathans   Navigation in modal pages is not currently supported in NativeScript applications but a feature request is logged and our team is assessing if this is a viable scenario. Once we have more info about this we will update the post [here](https://github.com/NativeScript/NativeScript/issues/3753)

As a workaround, you can use the [closeCallback ](http://docs.nativescript.org/api-reference/interfaces/_ui_page_.shownmodallydata.html#closecallback)to initiate navigation
