### ISSUE TITLE
NavigationExtras with RouterExtensions + clearHistory?

### ISSUE THREAD

**Issue by sam0829** [NativeScript/nativescript-angular#610]
I want to pass the data to another page while navigating. for that, I was using

`this.router.navigate(["/SignatureOptionVC"], navigationExtras);`

But then, I needed to clear the back-stack/history as well, so I found that I can navigate through
`RouterExtensions `with `clearHistory: true` flag. But it seems it doesn't support `navigationExtras`.

Is there any way I can clear history + pass navigationExtras?

**Comment by NickIliev** [comment]
Hi @sam0829 

You can pass navigation options like this:
```
this.routerExtensions.navigate(["/first"], {
    clearHistory: true,
    transition: {
        name: "flip",
        duration: 2000,
        curve: "linear"
    }
});
```
More about navigation option in NG+Angular-2 [here](http://docs.nativescript.org/angular/core-concepts/angular-navigation.html#navigation-options)

**Comment by sam0829** [comment]
@NickIliev thanks for your quick reply, I'll try this & close the question. Thanks again :)

**Comment by sam0829** [comment]
@NickIliev I want to pass data from one screen to another while using `routerExtensions.navigate()`
If I looked correct, then it only supports following :

` clearHistory?: boolean;
    animated?: boolean;
    transition?: NavigationTransition;`

But I want clearHistory + data passing.

Is there any way to achieve this using `routerExtensions`?

because my main problem is I want to cleat the back stack while navigating & at the same time I want to pass the data to the page I am navigating

**Comment by NickIliev** [comment]
@sam0829 passing context within pages differs from vanilla NativeScript.
Here you can find the documentation article about [passing parameters](http://docs.nativescript.org/angular/core-concepts/angular-navigation.html#passing-parameter) and [here you can find a sample](http://stackoverflow.com/a/38983109/4936697) which is using the native API but the logic is the same with the wrapped PageRoute instead of the @angular ActivatedRoute
