### ISSUE TITLE
Create Plugin

### ISSUE THREAD

**Issue by mohitgorakhiya** [NativeScript/nativescript-angular#630]
Hi,

I have iOS library with .a file and .h files.
And now I want to use these inside Nativescript.
So is it require to nativescript plugin for these?
If Yes how to create pluging for .a and .h files?
If no then how to use inside nativescript?

Thanks,
Mohit.

**Comment by NickIliev** [comment]
@mohitgorakhiya 

Whether your plugin will use CocoaPod or the native iOS API you will need to follow the rules for creating a plugin in NativeScript. More about [creating plugins](http://docs.nativescript.org/plugins/PLUGINS.html) and [marshalling](http://docs.nativescript.org/runtimes/ios/marshalling/Marshalling-Overview) (data conversion in the iOS case - conversion from Objective-C to JavaScript and the other way around). When using CocoaPods libraries you also need to create a Podfile like described [here](http://docs.nativescript.org/plugins/cocoapods). 

In your case, if the Objective-C files are depending entirely on the native API then you can create your plugin following the marshalling techniques. Very basic example on how to convert Objective-C to javaScript you can find [here](http://docs.nativescript.org/runtimes/ios/getting-started/HelloWorld)

**Comment by mohitgorakhiya** [comment]
Thanks for ur reply.
If i have 3rd party ios framework and i want to use  inside nativescript
than how i can use?

**Comment by NickIliev** [comment]
@mohitgorakhiya you can take a look at [this artcile](https://docs.nativescript.org/runtimes/ios/how-to/Use-Native-Libraries)

**Comment by lukecaan** [comment]
I'm also trying to use a native Static Framework inside of a Nativescript project. That article you referenced doesn't help because it doesn't look like the instructions point to the correct article. the link to 'Create a plugin containing the already built binary and headers.' points to this page: https://docs.nativescript.org/plugins/plugins .. so can anyone outline how to turn a static framework into a plugin for nativescript?
