### ISSUE TITLE
Question: NativeScriptPlatformRef.bootstrapModule/bootstrapModuleFactory returns null?

### ISSUE THREAD

**Issue by m-abs** [NativeScript/nativescript-angular#635]
I'm just wondering why it's necessary for bootstrapModule/bootstrapModuleFactory to return null to make the compiler happy and not a Promise like the type declaration says they should? 

See here:
https://github.com/NativeScript/nativescript-angular/blob/master/nativescript-angular/platform-common.ts#L77

I had hoped to use the promise to log start up time for our app.

**Comment by vakrilov** [comment]
Returning promise form the `bootstrapModule/bootstrapModuleFactory` was the initial idea and no doubt it would have been useful. However, we hit a limitation that does not allow us to do that. 

**The reason:** The bootstrap method should call [`application.start()`](https://github.com/NativeScript/nativescript-angular/blob/master/nativescript-angular/platform-common.ts#L98).  Any code after the `start()` will **not** be executed in IOS, as it falls after the application loop. So even if we return a promise - you will never have the chance to attach the `then` and `catch` to it in order to process it. 

That said, we have done a bunch of performance tests and we usually use the lifecycle hooks of the ApplicationModule or the first component that is rendered to record the start-up time.

**Comment by m-abs** [comment]
Thank you very much for the explanation, it makes sense
