### ISSUE TITLE
Angular 4 updates 

### ISSUE THREAD

**Issue by hiddencaliber** [NativeScript/nativescript-angular#722]
Hi,

Please share the road-map (if any) tosupport Angular 4.

Thanks.

**Comment by vchimev** [comment]
Hi @hiddencaliber,

The support of Angular 4 is already in the *release* branch and we are executing final tests. If everything goes as expected, we are going to release it tomorrow as **nativescript-angular@1.5.0**.

**Comment by patrickpereira** [comment]
Hi @vchimev 

I've just updated to Angular 4 and nativescript-angular 1.5, normal JIT compilation works fine, but when I try to run AOT, I get this error:

ERROR in Error encountered resolving symbol values statically. Calling function 'ɵmakeDecorator', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol Injectable in /Users/patrickpereira/lazy/K-cal/node_modules/nativescript-angular/node_modules/@angular/core/core.d.ts, resolving symbol ɵf in /Users/patrickpereira/lazy/K-cal/node_modules/nativescript-angular/node_modules/@angular/core/core.d.ts, resolving symbol ɵf in /Users/patrickpereira/lazy/K-cal/node_modules/nativescript-angular/node_modules/@angular/core/core.d.ts

All help appreciated :-)

**Comment by danielgek** [comment]
@patrickpereira have a look at [this](https://github.com/angular/angular-cli/issues/3707) ?

**Comment by patrickpereira** [comment]
@danielgek, thanks for the link - what exactly am I looking for, doesn't really mention Angular 4 in there?

On Angular 2.4.10 and nativescript-angular 1.4.1, my AOT compilation was working just fine, I've downgraded for now untill a solution is found.

**Comment by sis0k0** [comment]
Hey @patrickpereira,

Make sure you update all your angular packages (including the router) to 4.0. This usually happens when you have missmatching versions and end up with node_modules folder in `node_modules/nativescript-angular`. Please check if that is the case. If you still have a problem, please share your package.json. Thank you!

**Comment by patrickpereira** [comment]
Hi @sis0k0 

You were right I have extra node_modules folder, I think it happened because I upgraded to 1.5 before I upgraded Angular to 4.0.0, got it fixed by removing nativescript-angular and adding it again.

Same issue happens when I try to upgrade to 4.0.1, it will then create the extra node_modules folder with angular 4.0.0 inside, which breaks AOT. So for now I'm sticking with 4.0.0.

**Comment by sis0k0** [comment]
@patrickpereira,

I'm glad that solved the problem. We'll unpin the angular version in the next patch of nativescript-angular (1.5.1), which we plan to release later today. If you have other problems or any feedback, we'd be happy to hear!

**Comment by sis0k0** [comment]
Fixed with 1.5.1 patch.
