### ISSUE TITLE
How to display multiple long labels as sentence

### ISSUE THREAD

**Issue by bachras** [NativeScript/nativescript-angular#766]
Hi everyone, 

I am facing problem for the last two days and tried other forums ( http://stackoverflow.com/questions/43541629/how-to-display-multiple-nativescript-variables-as-sentence , https://discourse.nativescript.org/t/how-to-display-multiple-nativescript-variables-as-sentence/1096/7), but nobody seems to know the solution. Could anybody help me here?

I have multiple label, but for simplicity let's use two variables
`str1 = "Button Button Button";`
`str2 = "Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test";`

What I want to achieve: 

`Button Button Button Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test`

I have tried every layout and all different combination, but nothing worked. It works fine with FlexboxLayout and when both string are short and can fit in one line. Any help would be appreciated as I am out of ideas. Thanks

**Comment by NickIliev** [comment]
Please consider leaving UI related question for the community channels as our forum where you have originally posted this question. We are trying to keep the repository strictly for reporting issues, bugs, and abnormal behavoir.

Apart from that I think you can solve this issue by using FlexLayour

e.g.
```
<FlexboxLayout flexWrap="wrap" alignContent="flex-start" >
    <Label text="Hello" ></Label>
    <Label text="how are you? how are you? how are you?" ></Label>
    <Label text="Button" t></Label>
    <Label text="Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test Test" ></Label>
</FlexboxLayout>
```
FlexboxLayout is relatively new component introduced to nativeScrtip in order to ease the development for users with web background. The component supports only a subset of properties as described [here](https://docs.nativescript.org/cookbook/ui/layouts/flexbox-layout) and you can find Angular examples [here](https://github.com/NativeScript/nativescript-sdk-examples-ng/tree/release/app/ui-category/layouts)

**Comment by bachras** [comment]
@NickIliev thanks for prompt reply, I know I shouldn't post UI related questions here, but none of the suggestions from forum worked. I tried your code and it works until I fix the width or use in GridLayout. Do you know what the issue could be?

**Comment by brandart** [comment]
@bachras did you manage to fix this problem or what did you do?

**Comment by asharghi** [comment]
Anyone?

**Comment by sergii-hq** [comment]
Anyone?
