### ISSUE TITLE
button on tabview 

### ISSUE THREAD

**Issue by nelsonwilliam11** [NativeScript/nativescript-angular#824]
is it possible to set  tap event in the  tabview tabItem  with angular??????

**Comment by NickIliev** [comment]
@nelsonwilliam11 to handle the changed tabs you have **selectedIndex** property and **selectedIndexChange** event which should be considerably more useful as the index might change not only on tap but also on swipe left/right due to the nature of the TabView. Examples [here](https://github.com/NativeScript/nativescript-sdk-examples-ng/blob/master/app/ui-category/tab-view/basic-tab-view/basic-tab-view.component.html#L2).

So instead of using **tap** event, handling **selectedIndex** should do the job for controlling your TabView. Here is the API reference for [selectedIndexChangeEventData](http://docs.nativescript.org/api-reference/interfaces/_ui_tab_view_.selectedindexchangedeventdata.html)

Of course, you can always implement tap event for the containers of your tab items (if that is your goal) but not the TabItems itself
