### ISSUE TITLE
Is there any code or solution or Refer a friend for app from nativescript angular 2

### ISSUE THREAD

**Issue by JaganJonnala** [NativeScript/nativescript-angular#919]
Refer a Friend for Android app by Nativescript

**Comment by NickIliev** [comment]
@JaganJonnala not exactly sure what the issue is but if you are looking for code base for a sample application written with NativeScript and Angular-2 I would suggest taking a look [at this tutorial](http://docs.nativescript.org/angular/tutorial/ng-chapter-1.html) (the source code of the entire application is also available)
