### ISSUE TITLE
[BUG] HTTP returns 200 status code on invalid host URL or when without internet connection

### ISSUE THREAD

**Issue by felipebernardes** [NativeScript/nativescript-angular#927]
Hey Folks,

Whenever I make an (angular) HTTP request without internet connection and/or for an invalid host url, I'm getting the following error:

> JS:     "originalStack": "Error: java.net.UnknownHostException: Unable to resolve host \"xptoo.comm\": No address associated with hostname\n    at ZoneAwareError (file:///data/data/br.com.tegra.go.coletor/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:993:33)\n    at onRequestComplete (file:///data/data/br.com.tegra.go.coletor/files/app/tns_modules/tns-core-modules/http/http-request/http-request.js:44:34)\n    at Object.onComplete (file:///data/data/br.com.tegra.go.coletor/files/app/tns_modules/tns-core-modules/http/http-request/http-request.js:36:13)",
JS:     "zoneAwareStack": "Error: java.net.UnknownHostException: Unable to resolve host \"xptoo.comm\": No address associated with hostname\n    at onRequestComplete (file:///data/data/br.com.tegra.go.coletor/files/app/tns_modules/tns-core-modules/http/http-request/http-request.js:44:34) [<root>]\n    at Object.onComplete (file:///data/data/br.com.tegra.go.coletor/files/app/tns_modules/tns-core-modules/http/http-request/http-request.js:36:13) [<root>]",
JS:     "__zone_symbol__currentTask": {
JS:       "type": "microTask",
JS:       "state": "notScheduled",
JS:       "source": "Promise.then",
JS:       "zone": "angular",
JS:       "cancelFn": null,
JS:       "runCount": 0
JS:     }
JS:   },
JS:   "status": 200,
JS:   "ok": true,
JS:   "statusText": "",
JS:   "headers": {},
JS:   "type": 3,
JS:   "url": null
JS: }

Anyone had a similar problem?

Thanks in advance!

**Comment by NickIliev** [comment]
@felipebernardes can you provide the actual code that stands behind the HTTP request and also please let us know if you are experiencing the issue on iOs or on Android (or on both). Is this reproducible on your side with [these examples](https://github.com/NativeScript/nativescript-sdk-examples-ng/tree/master/app/http)

**Comment by abdulhaq-e** [comment]
Yes I had a similar problem. I was using `localhost` as the request url then I found out that the loopback device on emulators is not `localhost`. The JS response was the same as the one you posted it.

**Comment by SynsoftDev** [comment]
JS: {"originalStack":"Error: java.net.UnknownHostException: Unable to resolve host \"api.everlive.com\": No address associated with hostname\n    at ZoneAwareError (file:///data/data/org.nativescript.Groceries/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:993:33)\n    at onRequestComplete (file:///data/data/org.nativescript.Groceries/files/app/tns_modules/tns-core-modules/http/http-request/http-request.js:44:34)\n    at Object.onComplete (file:///data/data/org.nativescript.Groceries/files/app/tns_modules/tns-core-modules/http/http-request/http-request.js:36:13)","zoneAwareStack":"Error: java.net.UnknownHostException: Unable to resolve host \"api.everlive.com\": No address associated with hostname\n    at onRequestComplete (file:///data/data/org.nativescript.Groceries/files/app/tns_modules/tns-core-modules/http/http-request/http-request.js:44:34) [<root>]\n    at Object.onComplete (file:///data/data/org.nativescript.Groceries/files/app/tns_modules/tns-core-modules/http/http-request/http-request.js:36:13) [<root>]","__zone_symbol__currentTask":{"type":"microTask","state":"notScheduled","source":"Promise.then","zone":"angular","cancelFn":null,"runCount":0}}

**Comment by EricRobertBrewer** [comment]
I have the same issue. I call out to our staging API which uses a different port than `22`:

    const url = 'https://my-pre.autonetmobile.net:8443/api_bridge/send_link_to_reset_password';
    const params = {
        email: 'myusername@myemail.com'
    };
    const options = {};
    this.http.post(url, params, options).map((value: Response) => {
            console.log('api response='+JSON.stringify(value));
            return value.json();
        }, (error) => {
            console.error('error='+JSON.stringify(error));
        });

Gives me:

    JS: error={"_body":{"__zone_symbol__currentTask":{"type":"microTask","state":"notScheduled","source":"Promise.then","zone":"angular","cancelFn":null,"runCount":0}},"status":200,"ok":true,"statusText":"","headers":{},"type":3,"url":null}

But when I use our production host, `https://my-autonetmobile.net/api_bridge/send_link_to_reset_password`, I get no error.

Am I using the port incorrectly?

**Comment by abdulhaq-e** [comment]
@EricRobertBrewer Is your server expecting a JSON? If so, I think you need to `JSON.stringify(params)` and if it's expecting `form-encoded` data you need to send the params as `email=......` and change the `Content-Type` header.

**Comment by EricRobertBrewer** [comment]
JSON format is not the issue.
I tried sending the same request to our production URL listed above which doesn't specify a port. The server responds to this request.

**Why can't I specify a port when sending an HTTP request?**

**Comment by mohitkhanna1994** [comment]
even i am facing the same issue


System.err: java.net.UnknownHostException: Unable to resolve host "api.everlive.
com": No address associated with hostname
System.err:     at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.j
ava:125)
System.err:     at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.
java:74)
System.err:     at java.net.InetAddress.getAllByName(InetAddress.java:752)
System.err:     at com.android.okhttp.internal.Network$1.resolveInetAddresses(Ne
twork.java:29)
System.err:     at com.android.okhttp.internal.http.RouteSelector.resetNextInetS
ocketAddress(RouteSelector.java:187)
System.err:     at com.android.okhttp.internal.http.RouteSelector.nextProxy(Rout
eSelector.java:156)
System.err:     at com.android.okhttp.internal.http.RouteSelector.next(RouteSele
ctor.java:98)
System.err:     at com.android.okhttp.internal.http.HttpEngine.createNextConnect
ion(HttpEngine.java:345)
System.err:     at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngin
e.java:328)
System.err:     at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpE
ngine.java:246)
System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute
(HttpURLConnectionImpl.java:457)
System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect
(HttpURLConnectionImpl.java:126)
System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutp
utStream(HttpURLConnectionImpl.java:257)
System.err:     at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.
getOutputStream(DelegatingHttpsURLConnection.java:218)
System.err:     at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOut
putStream(HttpsURLConnectionImpl.java)
System.err:     at org.nativescript.widgets.Async$Http$RequestOptions.writeConte
nt(Async.java:313)
System.err:     at org.nativescript.widgets.Async$Http$HttpRequestTask.doInBackg
round(Async.java:536)
System.err:     at org.nativescript.widgets.Async$Http$1.run(Async.java:482)
System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolE
xecutor.java:1133)
System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPool
Executor.java:607)
System.err:     at org.nativescript.widgets.Async$PriorityThreadFactory$1.run(As
ync.java:52)
System.err:     at java.lang.Thread.run(Thread.java:761)
System.err: Caused by: android.system.GaiException: android_getaddrinfo failed:
EAI_NODATA (No address associated with hostname)
System.err:     at libcore.io.Posix.android_getaddrinfo(Native Method)
System.err:     at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java
:55)
System.err:     at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.j
ava:106)
System.err:     ... 21 more
JS: {"originalStack":"Error: java.net.UnknownHostException: Unable to resolve ho
st \"api.everlive.com\": No address associated with hostname\n    at ZoneAwareEr
ror (file:///data/data/org.nativescript.WSATABTEMPLATE/files/app/tns_modules/nat
ivescript-angular/zone-js/dist/zone-nativescript.js:993:33)\n    at onRequestCom
plete (file:///data/data/org.nativescript.WSATABTEMPLATE/files/app/tns_modules/t
ns-core-modules/http/http-request/http-request.js:45:34)\n    at Object.onComple
te (file:///data/data/org.nativescript.WSATABTEMPLATE/files/app/tns_modules/tns-
core-modules/http/http-request/http-request.js:37:13)","zoneAwareStack":"Error:
java.net.UnknownHostException: Unable to resolve host \"api.everlive.com\": No a
ddress associated with hostname\n    at onRequestComplete (file:///data/data/org
.nativescript.WSATABTEMPLATE/files/app/tns_modules/tns-core-modules/http/http-re
quest/http-request.js:45:34) [<root>]\n    at Object.onComplete (file:///data/da
ta/org.nativescript.WSATABTEMPLATE/files/app/tns_modules/tns-core-modules/http/h
ttp-request/http-request.js:37:13) [<root>]","__zone_symbol__currentTask":{"type
":"microTask","state":"notScheduled","source":"Promise.then","zone":"angular","c
ancelFn":null,"runCount":0}}


thanks in advance...

**Comment by kumarandena** [comment]
I am also getting same error on android,

`JS: Error Sync {"_body":{"__zone_symbol__currentTask":{"type":"microTask","state":"notScheduled","source":"Promise.then","zone":"angular","cancelFn":null,"runCount":0}},"status":200,"ok":true,"statusText":"","headers":{},"type":3,"url":null}
`

This is how i am making http post call,

this.http.post("http://182.76.**.***:8080/CentralAud/aud/ism/synchronize/" + syncData['data'].audType + "/" + syncData['data'].cid, fileData,
                                { headers: headers })
                                .map(response => response)
                                .subscribe(response => {
                                    console.log("Sync ", JSON.stringify(response));
                                }, error => {
                                    console.log("Error Sync", JSON.stringify(error))
                                });

 @NickIliev  & @EricRobertBrewer Any update/suggestion on this?

**Comment by Nileshdcool** [comment]
did anyone found any resolution to the above-related bug? Even I am facing this problem when I  try to connect my localhost API. I am trying to call my app to my locally hosted IIS web api..

{
JS:   "headers": {
JS:     "normalizedNames": {},
JS:     "lazyUpdate": null,
JS:     "headers": {}
JS:   },
JS:   "status": 0,
JS:   "statusText": "Unknown Error",
JS:   "url": "http://udcraft.api.com/connect/token",
JS:   "ok": false,
JS:   "name": "HttpErrorResponse",
JS:   "message": "Http failure response for http://udcraft.api.com/connect/token: 0 Unknown Error",
JS:   "error": {
JS:     "originalStack": "Error: java.net.UnknownHostException: Unable to resolve host \"udcraft.api.com\": No address associated with hostname\n    at new ZoneAwareError (file:///data/data/org.udcrafts.UDCraftsChartererApp/files/app/vendor.js:91672:33)\n    at onRequestComplete (file:///data/data/org.udcrafts.UDCraftsChartererApp/files/app/vendor.js:98626:34)\n    at Object.onComplete file: node_modules\@nativescript\core\http\http-request\http-request.android.js:43:0
JS:   }
JS: }

**Comment by NathanaelA** [comment]
The Stack shows this error message:
`"originalStack": "Error: java.net.UnknownHostException: Unable to resolve host "udcraft.api.com"`
This means your phone can't resolve the domain name `udcraft.api.com` so you need to fix your dns so that it knows what that dns address is.
